#build
FROM golang:1.10 AS build

WORKDIR /go/src/github.com/jonnywei/multistage-go

ADD . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

CMD ["./multistage-go"]


FROM alpine:latest AS certs
RUN apk --update add ca-certificates




FROM scratch AS prod

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

COPY --from=build /go/src/github.com/jonnywei/multistage-go/multistage-go .

CMD ["./multistage-go"]
